// 0001 | // This file was generated by Prisma, and assumes you have installed the following:
// 0002 | // npm install --save-dev prisma dotenv
// 0003 | import "dotenv/config";
// 0004 | import { defineConfig } from "prisma/config";
// 0005 | 
// 0006 | export default defineConfig({
// 0007 |   schema: "prisma/schema.prisma",
// 0008 |   migrations: {
// 0009 |     path: "prisma/migrations",
// 0010 |   },
// 0011 |   datasource: {
// 0012 |     url: process.env["DATABASE_URL"],
// 0013 |   },
// 0014 | });
